spring.application.name=auth-service
server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce_auth_db
spring.data.mongodb.auto-index-creation=true
management.endpoints.web.exposure.include=health,info
jwt.secret=EcommerceMicroservicesSecretKeyForJwtAuthentication2026Secure
jwt.expiration=86400000
