server.port=8761
spring.application.name=service-registry
# Eureka Server should not register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Eureka server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
