services:

  mongodb:
    image: mongo:8
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
      SPRING_APPLICATION_NAME: service-registry
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ecommerce_auth_db
      SPRING_CONFIG_IMPORT: optional:application-secrets.properties
    depends_on:
      - mongodb
    restart: unless-stopped

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ecommerce_product_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - mongodb
      - service-registry
    restart: unless-stopped

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/ecommerce_order_db
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - mongodb
      - service-registry
      - product-service
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - service-registry
      - auth-service
      - product-service
      - order-service
    restart: unless-stopped

volumes:
  mongodb_data:
