package com.ecommerce.order.dto;

import com.ecommerce.order.model.OrderStatus;
import com.ecommerce.order.model.PaymentStatus;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Schema(description = "Response containing complete order details")
public record OrderResponse(

        @Schema(
                description = "Unique identifier of the order",
                example = "68a1f2c34d1234567890abcd"
        )
        String id,

        @Schema(
                description = "Unique order number generated by the system",
                example = "ORD-20260821-001"
        )
        String orderNumber,

        @Schema(
                description = "Unique ID of the customer who placed the order",
                example = "CUST-001"
        )
        String customerId,

        @Schema(
                description = "List of products included in the order"
        )
        List<OrderItemResponse> items,

        @Schema(
                description = "Total amount of the order",
                example = "139998.00"
        )
        BigDecimal totalAmount,

        @Schema(
                description = "Current status of the order",
                example = "CONFIRMED"
        )
        OrderStatus status,

        @Schema(
                description = "Current payment status of the order",
                example = "PENDING"
        )
        PaymentStatus paymentStatus,

        @Schema(
                description = "Date and time when the order was created",
                example = "2026-08-21T18:30:00"
        )
        LocalDateTime createdAt
) {
}